server:
  port: 8081
  servlet:
    context-path: /admin

eureka:
  instance:
    prefer-ip-address: true
    # hostname: 172.20.0.1
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl.defaultZone: http://discovery-server:8761/eureka


spring:
  data:
    mongodb:
      uri: mongodb://10.152.0.2:27017
      username: rooot
      password: aASDFGHWERTYUIOVBNMBNXCVB234567SDFGHJ
      database: insurance_admin_service_db