server:
  port: 8081
  servlet:
    context-path: /admin

eureka:
  instance:
    prefer-ip-address: true
    hostname: 172.20.0.1
    client:
      service-url:
        defaultZone: http://discovery-server:8761/eureka


spring:
  data:
    mongodb:
      uri: mongodb://172.20.0.1:27017
      database: insurance_admin_service_db