server:
  port: 8081
  servlet:
    context-path: /admin

eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: insurance_admin_service_db