server:
  port: 7090
  servlet:
    context-path: /auth
jwt:
  auth:
    converter:
      resource-id: authenticationClientId
keycloak:
  realm: cqu-g4-insurance
  domain: localhost:7080
  adminClientId: admin-cli
  adminClientSecret: FrsQh56Xjy5JAMBfj4m1vI6ahsiu82vd
  client: authenticationClientId
  urls:
    auth: http://${keycloak.domain}
spring:
  profile:
    active: dev
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://${keycloak.domain}/realms/${keycloak.realm}

eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
