server:
  port: 7090
  servlet:
    context-path: /auth
jwt:
  auth:
    converter:
      resource-id: authenticationClientId
keycloak:
  realm: cqu-g4-insurance
  domain: keycloak.csangharsha.com.np
  adminClientId: admin-cli
  adminClientSecret: ngiyvUrmDHUa7TeuUHhv1AB65p7Ql0ul
  client: authenticationClientId
  clientSecret: HYF9IXrP97fnAZIFOe5eEmy1v3wFb44e
  urls:
    auth: http://${keycloak.domain}
spring:
  profile:
    active: dev
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://${keycloak.domain}/realms/${keycloak.realm}

eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl.defaultZone: http://discovery-server:8761/eureka
