server:
  port: 8082
  servlet:
    context-path: /therapy-provider

eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: insurance_therapy_provider_service_db