server:
  port: 8083
  servlet:
    context-path: /users

eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl.defaultZone: http://discovery-server:8761/eureka

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: insurance_user_service_db