server:
  port: 8083
  servlet:
    context-path: /users

eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl.defaultZone: http://discovery-server:8761/eureka

spring:
  data:
    mongodb:
      database: insurance_user_service_db
      uri: mongodb://10.152.0.2:27017
      username: rooot
      password: aASDFGHWERTYUIOVBNMBNXCVB234567SDFGHJ