server:
  port: 8083
  servlet:
    context-path: /users

eureka:
  instance:
    prefer-ip-address: true
    hostname: 172.20.0.1

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: insurance_user_service_db